Myaccount/urls.py
from django.urls import path

from .views import profile, profile_update

app_name = "Myaccount"

urlpatterns = [
    path(r'profile/', profile, name='profile'),
    path(r'profile/update/', profile_update, name='profile_update'),
]

blog/urls.py
from django.urls import path
from blog.views import IndexView, DetailView, CategoryView, TagView, ArchiveView, MySearchView

app_name = 'blog'

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),  # 首页
    path(r'article/<slug>/', DetailView.as_view(), name='article'),  # 文章详情页
    path(r'category/<slug>', CategoryView.as_view(), name='category'),  # 分类文章
    path(r'tag/<slug>', TagView.as_view(), name='tag'),   # 标签文章
    path(r'archive/', ArchiveView.as_view(), name='archive'), # 归档
    path(r'search/', MySearchView.as_view(), name='search')   # 全文搜索
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # 导入static
from django.conf import settings  # 导入settings

app_name = 'blog'

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),  # blog
    path(r'account/', include('allauth.urls')), # allauth
    path(r'account/', include('Myaccount.urls', namespace='accounts'))  # Myaccount
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Myaccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class User(AbstractUser):
    nickname = models.CharField(max_length=10, blank=True, null=True, verbose_name='昵称')
    link = models.URLField('', blank=True, help_text='提示：网址必须填写以http开头的完整形式')
    avatar = ProcessedImageField(upload_to='avatar', default='avatar/default.png',verbose_name='头像',
                                 processors=[ResizeToFill(100,100)],format='JPEG',options={'quality':95})

    class Meta:
        db_table = 'user'
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if len(self.avatar.name.split('/')) == 1:
            self.avatar.name = self.username + '/' + self.avatar.name
        super(User, self).save()

blog/models.py
from django.db import models
from django.shortcuts import reverse
import markdown
import datetime


class Keyword(models.Model):
    """关键词模型"""
    name = models.CharField(max_length=20, default='')

    class Meta:
        db_table = 'keyword'
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


class Tag(models.Model):
    """标签模型"""
    name = models.CharField(max_length=20, default='')
    slug = models.SlugField(unique=True, default='')

    class Meta:
        db_table = 'tag'
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

    def get_article_list(self):
        '''返回当前标签下所有发表的文章列表'''
        return Article.objects.filter(tags=self)

class Category(models.Model):
    """文章分类模型"""
    name = models.CharField(max_length=20, default='')
    slug = models.SlugField(unique=True, default='')

    class Meta:
        db_table = 'category'
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self)


class Article(models.Model):
    """文章模型"""
    title = models.CharField(max_length=14, verbose_name='文章标题')
    author = models.CharField(max_length=10, verbose_name='作者', default='Ryan')
    summary = models.TextField(max_length=80, verbose_name='文章摘要')
    body = models.TextField(verbose_name='文章内容')
    image = models.ImageField(upload_to='summary_img/%Y%m%d/', default='summary_img/default.jpg')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='文章分类')
    tags = models.ManyToManyField(Tag, verbose_name='标签')

    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中的keywords，一般3-4个足够')

    class Meta:
        db_table = 'articles'
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])

    def update_view(self):
        # self.views += 1
        # self.save(update_fields=['views'])
        pass

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

    def date_format(self):
        print(datetime.date(self.create_date).isoformat())
        return datetime.date(self.create_date).isoformat()

Myaccount/forms.py
from django import forms
from .models import User

class ProfileForm(forms.Form):
 class Meta:
  model = User
  fields = ['nickname', 'link', 'avatar']

Myaccount/views.py
from django.shortcuts import render


def profile():
    pass


def profile_update():
    pass

blog/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.views import generic
from blog.models import Article, Tag, Category, Keyword

from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet


class IndexView(generic.ListView):
    model = Article
    template_name = 'index.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGINATE_BY', 8)
    paginate_orphans = getattr(settings, 'BASE_PAGINATE_ORPHANS', 2)


class DetailView(generic.DetailView):
    model = Article
    template_name = 'detail.html'
    context_object_name = 'article'


class CategoryView(generic.ListView):
    model = Article
    template_name = 'category.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', 8)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 2)

    def get_queryset(self, **kwargs):
        queryset = super(CategoryView, self).get_queryset()
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return queryset.filter(category=cate)


class TagView(generic.ListView):
    model = Article
    template_name = 'tag.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', 8)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 2)

    def get_queryset(self, **kwargs):
        queryset = super(TagView, self).get_queryset()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return queryset.filter(tags=tag)


class ArchiveView(generic.ListView):
    model = Article
    template_name = 'archive.html'
    context_object_name = 'articles'
    paginate_by = 200
    paginate_orphans = 50


class MySearchView(SearchView):
    context_object_name = 'search_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', 8)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 2)
    queryset = SearchQuerySet().order_by('-views')

templates/archive.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block base-files %}
    <link rel="stylesheet" href="{% static 'css/archive.css' %}">
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="card border-0 rounded-0 mb-3">
                    <div class="card-body f-16 archive">
                        <div class="archive-title px-2">
                            一共{% get_article_count %}篇文章，总计xxxxx字，评论数xxx
                        </div>
                        {% regroup articles by create_date.year as year_list %}
                        <ul class="pl-3 pl-sm-4">
                            {% for article in year_list %}
                                <li>{{ article.grouper }} 年
                                    {% regroup article.list by create_date.month as month_list %}
                                    <ul class="pl-3 pl-sm-4">
                                        {% for each in month_list %}
                                            <li>{{ each.grouper }} 月 (共 {{ each.list|length }} 篇)
                                                <ul class="pl-3 pl-sm-4">
                                                    {% for item in each.list %}
                                                        <li class="text-info">{{ item.create_date|date:'m-d' }}&nbsp;&nbsp;&nbsp;
                                                            <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                {% include 'tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
{% load tctip_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Ryan Code 个人博客{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.3.0/css/bootstrap.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- blog css-->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block base-files %}{% endblock %}
    {% load_tctip %}
</head>

<body class="bg-light">
    <!-- 导航栏 -->
    <header class="shadow">
    {% include 'tags/navbar.html' %}
    </header>
    <!--主体-->
    <main class="main-content">
        {% block base_content %}{% endblock %}
    </main>
    <!--回到顶部按钮-->
    <span class="text-center bg-white" id="backtop">
        <a class="fa fa-arrow-up" style="text-decoration: none;color: skyblue;" href=""></a>
    </span>
    <!--尾部-->
    <footer class="container-fluid mt-3 bg-dark">
        <div class="card-body text-center footer-font fs-15">
            <p class="mb-1">Copyright © 2020 Ryancode Powered by Django.</p>
            <p class="mb-1">沪ICP备xxxxxxxxxx号-x | 站长统计 | 网站已续航 xxx 天</p>
        </div>
    </footer>
</body>

<script src="{% static 'js/base.js'%}"></script>
</html>

templates/category.html
{% extends 'base.html' %}

{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {% include 'tags/articles.html' %}
            </div>
            <div class="col-lg-4">
                {% include 'tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block base-files %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        showProcessingMessages: false, //关闭js加载过程信息
        messageStyle: "none", //不显示信息
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
            inlineMath: [['$', '$'], ["\\(", "\\)"]],
            displayMath: [['$$', '$$'], ["\\[", "\\]"]],
            skipTags: ['h1', 'h2', 'h3', 'h4', 'h5'],
        },
        'HTML-CSS': {
            linebreaks: {automatic: true},
            availableFonts: ["STIX", "TeX"],    // 可选字体
            showMathMenu: false //禁用右键菜单
        }
    });
    MathJax.Hub.Queue(["Typeset", MathJax.Hub]);


    </script>
    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async>
    </script>
    <link rel="stylesheet" href="{% static 'css/md_css/default.css' %}">
{% endblock %}

{% block base_content %}
    <div class="container px-2 px-sm-5">
        <div class="card-body p-0">
            <ol class="breadcrumb border-0 rounded-0 mb-2 py-2">
                <li class="breadcrumb-item font-weight-bold"><i class="fa fa-home"></i><a href="{% url 'blog:index' %}">
                    首页 </a></li>
                <li class="breadcrumb-item font-weight-bolder"><a
                        href="{{ article.category.get_absolute_url }}"> {{ article.category }} </a></li>
                <li class="breadcrumb-item fs-15"> {{ article.title }} </li>
            </ol>
        </div>

        <div class="article-block card-body mb-2 p-3 bg-white">
            <h1 class="card-title text-center font-weight-bold text-info">{{ article.title }}</h1>
            <hr>
            <div class="text-center fs-12">
            <span class="mx-2" data-toggle="tooltip" data-placement="bottom"
                  title="最后编辑于{{ article.update_date }}">{{ article.create_date|date:"Y-m-d H:i" }}</span>
                <span class="mx-2">阅读 {{ article.views }}</span>
                <a class="mx-2 to-com" href="">评论 6</a>
            </div>
            <div class="article-body mt-3 px-1 px-md-3">
                {{ article.body_to_markdown | safe }}
                <blockquote class="blockquote mt-4 pl-2 pl-md-3 py-1 fs-15">
                    <p class="my-1 p-0"><span class="font-weight-bolder">版权声明：</span><span>如无特殊说明，文章均为原创，转载请注明出处</span>
                    </p>
                    <p class="my-1 p-0"><span
                            class="font-weight-bolder">本文链接：</span><span>https://www.xxx.com/xxx/</span></p>
                    <p class="my-1 p-0"><span class="font-weight-bolder">许可协议：</span><span><a href="">署名-非商业性使用 4.0 国际许可协议</a></span>
                    </p>
                </blockquote>
                <div class="tags-cloud my-3">
                    {% for tag in article.tags.all %}
                        <a class="tags text-white fs-15" href="">{{ tag }}</a>
                    {% endfor %}
                </div>
                <nav class="more-article">
                    <ul class="pagination justify-content-between fs-15">
                        <li class="page-item">
                            {% if article.get_pre %}
                                <a class="text-info" href="{{ article.get_pre.get_absolute_url }}"
                                   title="上一篇：{{ article.get_pre.title }}">
                                    <i class="fa fa-angle-double-left mr-1"></i>
                                    上一篇：{{ article.get_pre.title }}
                                </a>
                            {% endif %}
                        </li>
                        <li class="page-item">
                            {% if article.get_next %}
                                <a class="d-none d-lg-block text-info" href="{{ article.get_next.get_absolute_url }}"
                                   title="下一篇：{{ article.get_next.title }}">
                                    下一篇：{{ article.get_next.title }}
                                    <i class="fa fa-angle-double-right ml-1"></i>
                                </a>
                                <a class="align-content-start d-lg-none text-info"
                                   href="{{ article.get_next.get_absolute_url }}">
                                    <i class="fa fa-angle-double-right mr-2"></i>下一篇：{{ article.get_next.title }}
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {% include 'tags/articles.html' %}
            </div>
            <div class="col-lg-4">
                {% include 'tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/search/search.html
{% extends 'base.html' %}
{% load humanize %}
{% load highlight %}
{% load blog_tags %}

{% block base-files %}
<style>
    .highlighted {color: lightcoral;}
</style>
{% endblock %}


{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
            {% if query %}
                <div class="summary-list">
                    {% for article in search_list %}
                        <section class="summary-block p-1 p-lg-3 bg-white">
                            <h5 class="title d-inline-block pl-1">
                                <a href="{{ article.object.get_absolute_url }}" class="text-info"
                                   href="#">{% title_highlight article.object.title query %}</a></h5>
                            <span class="pub-date float-right mt-1 mr-3 fs-15">
                                <i class="fa fa-calendar mr-1" aria-hidden="true"></i>{{ article.object.create_date|naturalday:"Y-m-d" }}</span>
                            <div class="summary-img align-self-center modal-open fs-15 mt-3">
                                <a href="{{ article.object.get_absolute_url }}" title="{{ article.object.title }}">
                                    <img src="{{ article.object.image.url }}" alt="">
                                </a>
                                {% with article.object.body_to_markdown|safe as this_body %}
                                <span class="summary-text d-inline-block w-60 ml-1 ml-sm-3">{% highlight this_body with query max_length 80 %}</span>
                                {% endwith %}
                            </div>
                            <div class="summary-footer mt-3  fs-15">
                                <a href="#" title="查看该分类下更多文章">
                                    <i class="fa fa-book ml-2 mr-1" aria-hidden="true"></i>{{ article.object.category }}
                                </a>
                                <a href="#" class="float-right mr-3" title="查看文章评论">
                                    <i class="fa fa-comments mr-1" aria-hidden="true"></i>{{ article.object.views }}
                                </a>
                                <span class="float-right mr-4">
                                <i class="fa fa-eye mr-1" aria-hidden="true"></i>{{ article.object.views }}</span>
                            </div>
                        </section>
                        {% empty %}
                        <div class="p-3 mt-3 bg-white">暂时没有相应文章！</div>
                    {% endfor %}
                </div>
            {% endif %}
                {% include 'tags/pagecut.html' %}
            </div>
            <div class="col-lg-4">
                {% include 'tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tag.html
{% extends 'base.html' %}

{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {% include 'tags/articles.html' %}
            </div>
            <div class="col-lg-4">
                {% include 'tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tags/articles.html
{% load humanize %}

<div class="summary-list">
    {% for article in articles %}
        <section class="summary-block p-1 p-lg-3 bg-white">
            <h5 class="title d-inline-block pl-1"><a href="{{ article.get_absolute_url }}" class="text-info"
                                                     href="#">{{ article.title }}</a></h5>
            <span class="pub-date float-right mt-1 mr-3 fs-15">
                <i class="fa fa-calendar mr-1" aria-hidden="true"></i>{{ article.create_date|naturalday:"Y-m-d" }}
            </span>
            <div class="summary-img align-self-center modal-open fs-15 mt-3">
                <a href="{{ article.get_absolute_url }}" title="{{ article.title }}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="summary-text d-inline-block w-60 ml-1 ml-sm-3">{{ article.summary }}</span>
            </div>
            <div class="summary-footer mt-3  fs-15">
                <a href="{{ article.category.get_absolute_url }}" title="查看该分类下更多文章">
                    <i class="fa fa-book ml-2 mr-1" aria-hidden="true"></i>{{ article.category }}
                </a>
                <a href="#" class="float-right mr-3" title="查看文章评论">
                    <i class="fa fa-comments mr-1" aria-hidden="true"></i>{{ article.views }}
                </a>
                <span class="float-right mr-4">
                    <i class="fa fa-eye mr-1" aria-hidden="true"></i>{{ article.views }}
                </span>
            </div>
        </section>
    {% endfor %}
</div>

{% include 'tags/pagecut.html' %}

templates/tags/base_right.html
{% load blog_tags %}
{% load static %}

<div class="card1 px-0 mb-3 bg-white">
    <div class="card-header px-3 py-3 bg-white">
        <i class="fa fa-paper-plane mr-2"></i>个人空间
    </div>
    <div class="card-body my-2 text-center">
        <h3>Ryancode</h3>
        <p class="fs-15 mb-4">我于杀戮之中盛放，亦如黎明中的花朵</p>
        <div class="row">
            <div class="col" onmouseover="this.className = 'weixin weixin_on col';" onmouseout="this.className = 'weixin col';">
                <a class="" href="javascript:;"><img src="{% static 'img/wechat.png' %}" width="60px" height="60px" alt="扫码添加博主的微信"></a>
                <div class="weixin_nr fs-12">
                    <div class="arrow"></div>
                    <img class='weixin_qr' src="{% static 'img/WechatQR.jpg' %}" alt="">
                    扫码添加微信
                </div>
            </div>
            <div class="col">
                <a href="#"><img src="{% static 'img/github.png' %}" alt="转到博主的github"></a>
            </div>
            <div class="col">
                <a href="#"><img src="{% static 'img/rss.png' %}" alt="订阅博客"></a>
            </div>
        </div>
    </div>
    <div class="card-footer px-3 pt-2 text-center fs-15  bg-white">
        <div class="row">
            <div class="col">
                {% get_article_count as article_count %}
                <p class="card-numbers">{{ article_count }}</p>
                <p class="card-font">文章</p>
            </div>
            <div class="col">
                <p class="card-numbers">666</p>
                <p class="card-font">评论</p>
            </div>
            <div class="col">
                <p class="card-numbers">1234</p>
                <p class="card-font">浏览</p>
            </div>
        </div>
    </div>
</div>

<div class="card2 px-0 mb-3">
    <div class="card-header px-3 py-3 bg-white">
        <i class="fa fa-book mr-2 mb-0"></i>文章分类
    </div>
    <div class="card-body mb-2 p-0 ">
        {% get_category_list as categories %}
        <ul class="list-group list-group-flush fs-15">
            <li class="list-group-item">
                <a href="{% url 'blog:index' %}">全部文章</a>
                <span class="article-number text-center mr-2">{{ article_count }}</span>
            </li>
            {% for each_category in categories %}
                <li class="list-group-item">
                    <a href="{{ each_category.get_absolute_url }}">{{ each_category.name }}</a>
                    <span class="article-number text-center mr-2">{{ each_category.total_num }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="card3 px-0 mb-3 bg-white">
    <div class="card-header px-3 py-3 bg-white">
        <i class="fa fa-tags mr-2 mb-0"></i>标签云
    </div>
    <div class="card-body">
        <div class="tags-cloud">
            {% get_tag_list as tag_list %}
            {% for tag in tag_list %}
                <a class="tags text-white" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="card4 px-0 mb-3 bg-white">
    <div class="card-header px-3 py-3 bg-white">
        <i class="fa fa-link mr-2 mb-0"></i>友情链接
    </div>
    <div class="card-body fs-15">
        <div class="friend-link">
            <a href="#">xxx博客</a>
            <br>
            <a href="#">xxx博客</a>
            <br>
            <a href="#">xxx博客</a>
        </div>
    </div>
</div>

templates/tags/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-light blog-navbar bg-white">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Ryancode</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto mr-5">
            <li class="nav-item mr-5">
                <a class="nav-link" href="{% url 'blog:index' %}">首 页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-5">
                <a class="nav-link" href="{% url 'blog:archive' %}">归 档</a>
            </li>
            <li class="nav-item mr-5">
                <a class="nav-link" href="#">资 源</a>
            </li>
            <li class="nav-item dropdown mr-5">
                <a class="nav-link" href="#">留 言</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0 mr-5" role="search" method="get" action="{% url 'blog:search' %}">
            <input class="form-control re-control" type="search" name="q" placeholder="输入关键字搜索..." aria-label="Search">
            <button class="btn re-btn-outline-success my-2 my-sm-0 mr-3" type="submit">搜 索</button>
        </form>
        <ul class="navbar-nav mr-3">
            <li class="nav-item mr-2">
                <a class="nav-link py-md-2" href="{% url 'account_login' %}">登 录</a>
            </li>
        </ul>
    </div>
</nav>

templates/tags/pagecut.html
<div class="text-center page-cut my-3 fs-15">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="text-info page-cut-btn bg-light" >上一页</a>
    {% endif %}
    &nbsp;&nbsp;第&nbsp;{{ page_obj.number }}&nbsp;页&nbsp;/&nbsp;共&nbsp;{{ paginator.num_pages }}&nbsp;页&nbsp;&nbsp;
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="text-info page-cut-btn bg-light" >下一页</a>
    {% endif %}
</div>